services:
  frontend:
    image: ghcr.io/${GITHUB_REPO}/frontend:${IMAGES_TAG:-latest}
    build: client
    restart: always
    networks:
      - shared
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:8080/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: ghcr.io/${GITHUB_REPO}/backend:${IMAGES_TAG:-latest}
    build: server
    restart: always
    environment:
      DB_PASS_FILE: /run/secrets/db_pass
      POSTGRES_HOST: postgresql:5432
      REDIS_HOST: redis:6379
      RUSTFS_HOST: rustfs:9000
    depends_on:
      - postgresql
      - redis
      - rustfs
    networks:
      - shared
      - internal
    secrets:
      - db_pass
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:8080/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  caddy:
    image: "caddy:2.11.4-alpine"
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS}
    networks:
      - shared

  postgresql:
    image: "postgres:18.6-alpine3.24"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
      POSTGRES_DB: miostream
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d miostream"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - internal
    secrets:
      - db_pass

  redis:
    image: "redis:8.2.2-alpine"
    restart: always
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - internal

  rustfs:
    image: "rustfs/rustfs:latest"
    restart: always
    volumes:
      - rustfs-data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:9000/health/ready && curl --fail http://127.0.0.1:9001/rustfs/console/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - internal
    environment:
      RUSTFS_ACCESS_KEY_FILE: /run/secrets/rustfs_access_key
      RUSTFS_SECRET_KEY_FILE: /run/secrets/rustfs_secret_key
    secrets:
      - rustfs_access_key
      - rustfs_secret_key
    
networks:
  shared: {} # To be accessible for a proxy service
  internal: {} # Isolated

volumes:
  caddy-data: {}
  caddy-config: {}
  postgres-data: {}
  redis-data: {}
  rustfs-data: {}

secrets:
  db_pass:
    environment: DB_PASS
  rustfs_access_key:
    environment: RUSTFS_ACCESS_KEY
  rustfs_secret_key:
    environment: RUSTFS_SECRET_KEY
